# Generated by Django 5.0 on 2023-12-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('each', 'Each'), ('dz', 'Dozen'), ('tsp', 'Teaspoon'), ('tbsp', 'Tablespoon'), ('gram', 'Gram'), ('oz', 'Ounce'), ('lb', 'Pound')], default='each', max_length=50),
        ),
    ]
