# Generated by Django 5.0 on 2024-01-02 04:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 4, 58, 24, 416774, tzinfo=datetime.timezone.utc)),
        ),
    ]
